version: '3.3'
services:
   db:
     image: mysql:5.7
     container_name: db
     hostname: db
     restart: always
     networks:
        - mysql-net
     environment:
       MYSQL_ROOT_PASSWORD: instituto
       MYSQL_DATABASE: instituto
       MYSQL_USER: instituto
       MYSQL_PASSWORD: instituto
     volumes:
       - db:/var/lib/mysql
           
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:4.7
    restart: always
    networks:
        - mysql-net
    container_name: phpmyadmin
    hostname: phpmyadmin
    ports:
      - 8087:80
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: instituto
      UPLOAD_LIMIT: 200000K
      
volumes:
  db:
    name: db
networks:
  mysql-net:
    name: mysql-net

  