version: '3.3'
services:
   db:
     image: mysql:5.7
     volumes:
       - /opt/test:/var/lib/mysql
       - ./mysql-dump:/docker-entrypoint-initdb.d
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: instituto
       MYSQL_USER: instituto
       MYSQL_PASSWORD: instituto
     ports:
       - 5306:3306
   phpmyadmin:
    depends_on:
      - db
    image: phpmyadmin/phpmyadmin:4.7
    ports:
      - '9081:80'
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: root
   web:
    depends_on:
      - db
    image: tomcat:7.0.100-jdk8-openjdk
    volumes:
      - ./target/GestionInstitutoJavaFinal.war:/usr/local/tomcat/webapps/GestionInstitutoJavaFinal.war
    ports:
      - '9082:8080'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: instituto
      MYSQL_USER: instituto
      MYSQL_PASSWORD: instituto